[build]
builder = "nixpacks"
buildCommand = "cd backend && pip install -r requirements.txt"
providers = ["python"]

[variables]
PYTHON_VERSION = "3.11"
NIXPACKS_PYTHON_VERSION = "3.11"

[deploy]
startCommand = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[service]
rootDirectory = "." 